# Shell variables
# Generated by 'wal'
wallpaper='/home/ray/.config/wpg/wallpapers/Nature_Bright_2.jpg'

# Special
background='#0c0305'
foreground='#fffddb'
cursor='#e0c3a9'

# Colors
color0='#0c0305'
color1='#9F5329'
color2='#CE6F21'
color3='#9B6956'
color4='#78837B'
color5='#E3912D'
color6='#AC8D70'
color7='#e0c3a9'
color8='#2d0911'
color9='#db6828'
color10='#ff8e1b'
color11='#d98160'
color12='#8bba98'
color13='#ffbe28'
color14='#f2b67f'
color15='#fffddb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
