# Shell variables
# Generated by 'wal'
wallpaper='/home/ray/.config/wpg/wallpapers/Nature_Bright_5.jpg'

# Special
background='#15120f'
foreground='#ffffd9'
cursor='#dbcba6'

# Colors
color0='#15120f'
color1='#6B5333'
color2='#6D5D48'
color3='#906A33'
color4='#8D754E'
color5='#7D8474'
color6='#A9905E'
color7='#dbcba6'
color8='#2c261f'
color9='#956d38'
color10='#997a51'
color11='#c78c35'
color12='#c59b57'
color13='#a4bb86'
color14='#ecc069'
color15='#ffffd9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
